---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: emeraldsquad/concourse

inputs:
  - name: git-repo

outputs:
  - name: pushme

run:
  path: git-repo/ci-local/scripts/update-packages