---
name: tinyproxy

instance_groups:
- name: tinyproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: tinyproxy
    release: tinyproxy
    properties:
      "tinyproxy":
        instances: 
          - name: inst1
            port: 8088
            allowed_cidr: 0.0.0.0/0
            whitelisted_domains:
            - auth0.com
          - name: inst2
            allowed_cidr: 0.0.0.0/0
            port: 8089
            whitelisted_domains:
            - google.com
            - google.ca

stemcells:
- alias: default
  name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  version: "3468.17"

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-90000
  update_watch_time: 1000-90000
  serial: false


releases:
- name: tinyproxy
  version: 1.0.3
  url: https://github.com/emerald-squad/tinyproxy-release/releases/download/v1.0.3/tinyproxy-1.0.3.tgz
  sha1: eae616ff80e8dd1c0310761cdc9d24f6e4de0541
